id: P756FBA80
initial_creation_type: ocr
source_metadata:
  volumes:
    6eab72ac8c904ef8a336e8a172e59aff:
      base_file: v060.txt
      image_group_id: I1PD95905
      title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་ཚིག་གསལ་བ།
      total_pages: 1913
      volume_number: 60
